# Generated by Django 4.1.3 on 2022-11-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DaftarNama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100, verbose_name="Nama Anda")),
                (
                    "alamat",
                    models.CharField(max_length=100, verbose_name="Alamat Anda"),
                ),
                (
                    "kelamin",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")],
                        default="L",
                        max_length=1,
                        verbose_name="Jenis Kelamin",
                    ),
                ),
            ],
            options={
                "ordering": ["nama"],
                "unique_together": {("nama", "alamat")},
            },
        ),
    ]
