# Generated by Django 4.1.3 on 2022-11-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        default="-", max_length=200, verbose_name="Judul Artikel"
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        default="-", max_length=200, verbose_name="Pembuat"
                    ),
                ),
                (
                    "paragrafs",
                    models.TextField(max_length=5000, verbose_name="Artikel"),
                ),
                (
                    "tanggalbuat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Tanggal Pembuatan"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        default="", upload_to="img", verbose_name="Gambar untuk Artikel"
                    ),
                ),
            ],
            options={
                "ordering": ["tanggalbuat", "judul", "paragrafs"],
                "unique_together": {("judul", "creator", "paragrafs")},
            },
        ),
    ]
